
skillMetadata:
  sections:
    - name: GPS Coordinates
      fields:
        - type: label
          label: Provide your GPS coordinates to allow Mycroft to calculate sunrise/sunset times for your location. Your coordinates will stay safe with Mycroft. No remote service will be called using your data.
        - name: longitude
          type: text
          label: Longitude
          value: ""
        - name: latitude
          type: text
          label: Latitude
          value: ""